version: '3.9'

services:
    postgres:
        build: "./database"
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: mysecretpassword
            POSTGRES_DB: mydb
        restart: always
    
    nats: 
        image: "nats-streaming:0.9.2"
        restart: always

